"""
mcp deploy — central deploy entry point.

Usage:
    python3 deploy.py                          # TUI mode (arrow-key menus)
    python3 deploy.py <app> <target>           # CLI mode (non-interactive)
    python3 deploy.py --mail-ini <target>      # write shared jardyx-mail.ini only
"""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).parent
APPS_ROOT = REPO_ROOT.parent
LIB = REPO_ROOT / 'lib'

# Host-level SMTP config consumed by erikr/auth load_mail_config().
# Local + akadbrain are macOS + Homebrew → /opt/homebrew/etc. world4you is
# shared hosting; no writeable /etc path, so the file must be placed manually
# once (see docs/jardyx-mail-ini-prod.md) and we skip it here.
MAIL_INI_PATHS = {
    'local':     '/opt/homebrew/etc/jardyx-mail.ini',
    'akadbrain': '/opt/homebrew/etc/jardyx-mail.ini',
}


# ── Config ────────────────────────────────────────────────────────────────────

def load_config() -> dict:
    path = REPO_ROOT / 'config.yaml'
    with open(path) as f:
        return yaml.safe_load(f)


# ── Shared mail ini ───────────────────────────────────────────────────────────

def _render_mail_ini(smtp: dict) -> str:
    lines = ['# Generated by mcp/deploy.py — do not edit manually', '[smtp]']
    for key in ('host', 'port', 'user', 'password'):
        if key in smtp:
            lines.append(f'{key} = {smtp[key]}')
    return '\n'.join(lines) + '\n'


def write_jardyx_mail_ini(target: str, config: dict) -> None:
    """Write /opt/homebrew/etc/jardyx-mail.ini (or remote equivalent) for target.

    Pulls credentials from shared.smtp. Writes chmod 0640. Skips targets that
    do not have a managed path (e.g. world4you shared hosting)."""
    dest = MAIL_INI_PATHS.get(target)
    if dest is None:
        print(f'  (skipping jardyx-mail.ini on {target} — managed manually)')
        return

    smtp = config['shared']['smtp']
    body = _render_mail_ini(smtp)

    if target == 'local':
        _write_local_mail_ini(dest, body)
    else:
        _write_remote_mail_ini(config, target, dest, body)


def _write_local_mail_ini(dest: str, body: str) -> None:
    path = Path(dest)
    parent = path.parent
    if not parent.exists():
        print(f'  ERROR: {parent} does not exist; skipping jardyx-mail.ini', file=sys.stderr)
        return
    path.write_text(body)
    path.chmod(0o640)
    print(f'  wrote {dest}')


def _write_remote_mail_ini(config: dict, target: str, dest: str, body: str) -> None:
    t = config['shared']['targets'][target]
    ssh_host = t['ssh_host']
    ssh_user = t['ssh_user']
    ssh_key = t.get('ssh_key', '')

    with tempfile.NamedTemporaryFile('w', suffix='.ini', delete=False) as tmp:
        tmp.write(body)
        tmp_path = tmp.name

    scp = ['scp']
    ssh = ['ssh']
    if ssh_key:
        scp += ['-i', str(Path(ssh_key).expanduser())]
        ssh += ['-i', str(Path(ssh_key).expanduser())]

    try:
        subprocess.run(
            scp + [tmp_path, f'{ssh_user}@{ssh_host}:{dest}'],
            check=True,
        )
        subprocess.run(
            ssh + [f'{ssh_user}@{ssh_host}', f'chmod 640 {dest}'],
            check=True,
        )
        print(f'  wrote {ssh_user}@{ssh_host}:{dest}')
    finally:
        Path(tmp_path).unlink(missing_ok=True)


# ── Generate ──────────────────────────────────────────────────────────────────

def run_generate(app: str, target: str) -> None:
    """Call generate.py for the given app+target."""
    subprocess.run(
        [sys.executable, str(REPO_ROOT / 'generate.py'), '--app', app, '--target', target],
        check=True,
    )


# ── Deploy dispatch ───────────────────────────────────────────────────────────

def get_deploy_method(config: dict, app: str, target: str) -> str:
    """Return 'rsync_ssh' or 'rsync_local'.

    SSH is the only remote transport (FTP was retired). Targets with an
    ssh_host deploy over SSH; whether that delegates to the app's
    scripts/ssh_deploy.php is decided in deploy_rsync_ssh().
    """
    target_cfg = config['shared']['targets'].get(target, {})
    if 'ssh_host' in target_cfg:
        return 'rsync_ssh'
    return 'rsync_local'


def deploy_rsync_local(config: dict, app: str, target: str) -> None:
    dest = config['apps'][app]['deploy'][target]['dest']
    src = str(APPS_ROOT / app)
    subprocess.run(['bash', str(LIB / 'rsync.sh'), 'local', src, dest], check=True)


def deploy_rsync_ssh(config: dict, app: str, target: str) -> None:
    src = str(APPS_ROOT / app)
    # When the app ships scripts/ssh_deploy.php, rsync.sh delegates to it and
    # ignores dest/ssh_* args — the per-app script reads everything (including
    # the remote path) from its own config.yaml.
    # ssh_deploy.php is world4you-specific: it derives the remote path from the
    # per-app deploy.<target>.ftp_base_dir. Delegate only when that base dir is
    # configured (i.e. world4you); other ssh targets (akadbrain) fall through to
    # the generic rsync below with their explicit dest path.
    app_deploy = config['apps'][app].get('deploy', {}).get(target, {})
    ssh_deploy_php = APPS_ROOT / app / 'scripts' / 'ssh_deploy.php'
    if 'ftp_base_dir' in app_deploy and ssh_deploy_php.exists():
        subprocess.run(
            ['bash', str(LIB / 'rsync.sh'), 'ssh', src, '__delegated__'],
            check=True,
        )
        return
    dest = app_deploy['dest']
    t = config['shared']['targets'][target]
    subprocess.run(
        ['bash', str(LIB / 'rsync.sh'), 'ssh', src, dest,
         t['ssh_user'], t['ssh_host'], t.get('ssh_key', '')],
        check=True,
    )
    # rsync.sh excludes config.yaml; copy it separately so the app can boot.
    scp = ['scp']
    if t.get('ssh_key'):
        scp += ['-i', str(Path(t['ssh_key']).expanduser())]
    remote = f"{t['ssh_user']}@{t['ssh_host']}"
    subprocess.run(scp + [f'{src}/config.yaml', f'{remote}:{dest}/config.yaml'], check=True)


def run_migrations(app: str) -> None:
    """Run migrate.php if it exists in the app's scripts/ directory."""
    migrate = APPS_ROOT / app / 'scripts' / 'migrate.php'
    if migrate.exists():
        print(f'  Running migrations for {app}...')
        subprocess.run(['php', str(migrate)], check=True)


def do_deploy(config: dict, app: str, target: str) -> None:
    method = get_deploy_method(config, app, target)
    if method == 'rsync_ssh':
        deploy_rsync_ssh(config, app, target)
        # rsync_ssh delegates to scripts/ssh_deploy.php when present, which
        # runs its own remote migrations over SSH. Only call run_migrations
        # for the generic lib/rsync.sh path.
        if not (APPS_ROOT / app / 'scripts' / 'ssh_deploy.php').exists():
            run_migrations(app)
    else:
        deploy_rsync_local(config, app, target)
        run_migrations(app)


# ── CLI mode ──────────────────────────────────────────────────────────────────

def cli_deploy(app: str, target: str) -> None:
    config = load_config()
    apps = config['apps']

    if app not in apps:
        print(f'ERROR: unknown app "{app}". Known: {", ".join(apps)}', file=sys.stderr)
        sys.exit(1)

    valid_targets = apps[app]['targets']
    if target not in valid_targets:
        print(
            f'ERROR: "{target}" is not valid for {app}. '
            f'Valid targets: {", ".join(valid_targets)}',
            file=sys.stderr,
        )
        sys.exit(1)

    print(f'\n→ Generating config: {app} ({target})...')
    run_generate(app, target)
    print(f'→ Deploying {app} → {target}...')
    try:
        do_deploy(config, app, target)
    finally:
        if target != 'local':
            print(f'→ Restoring local config: {app}...')
            run_generate(app, 'local')
    print(f'\n✓ Done: {app} → {target}')


# ── TUI mode ──────────────────────────────────────────────────────────────────

def tui_deploy() -> None:
    import questionary
    from rich.console import Console
    from rich.panel import Panel

    console = Console()
    config = load_config()
    apps = list(config['apps'].keys())

    console.print(Panel(
        '[bold cyan]mcp deploy[/bold cyan]\nCentral deployment tool',
        expand=False,
    ))

    app = questionary.select('Select app:', choices=apps).ask()
    if not app:
        sys.exit(0)

    targets = config['apps'][app]['targets']
    target = questionary.select('Select target:', choices=targets).ask()
    if not target:
        sys.exit(0)

    if target != 'local':
        confirmed = questionary.confirm(
            f'Deploy {app} → {target}? This affects a live system.',
            default=False,
        ).ask()
        if not confirmed:
            console.print('[yellow]Aborted.[/yellow]')
            sys.exit(0)

    console.print(f'\n[cyan]→ Generating config: {app} ({target})...[/cyan]')
    run_generate(app, target)
    console.print(f'[cyan]→ Deploying {app} → {target}...[/cyan]')
    do_deploy(config, app, target)
    console.print(f'\n[green]✓ Done: {app} → {target}[/green]')


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description='Deploy apps — no args for TUI, or: deploy.py <app> <target>'
    )
    parser.add_argument('app', nargs='?', help='App name')
    parser.add_argument('target', nargs='?', help='Deploy target')
    parser.add_argument(
        '--mail-ini',
        metavar='TARGET',
        help='Write shared jardyx-mail.ini for TARGET and exit (no app deploy).',
    )
    args = parser.parse_args()

    if args.mail_ini:
        write_jardyx_mail_ini(args.mail_ini, load_config())
        return

    if args.app and args.target:
        cli_deploy(args.app, args.target)
    elif args.app or args.target:
        parser.error('Provide both <app> and <target>, or neither (for TUI mode).')
    else:
        tui_deploy()


if __name__ == '__main__':
    main()
